backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "projects"
    label: "Gallery Projects"
    label_singular: "Project"
    folder: "_projects"
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Project Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["commercial", "narrative", "events", "music", "bts"]}
      - {label: "Type", name: "type", widget: "select", options: ["video", "image"], default: "video"}
      - {label: "Video/Image Source", name: "src", widget: "string"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Tech Stack", name: "tech", widget: "list"}
      - {label: "Year", name: "year", widget: "string", default: "2024"}
